# Generated by Django 4.0.4 on 2022-06-15 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConverterString',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('raw_string', models.CharField(db_index=True, max_length=128, verbose_name='raw_string')),
                ('convert_string', models.CharField(db_index=True, max_length=128, verbose_name='convert_string')),
            ],
            options={
                'verbose_name': 'строка',
                'verbose_name_plural': 'строки',
                'ordering': ('-raw_string',),
            },
        ),
    ]
