# Generated by Django 4.0.4 on 2022-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConverterString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_string', models.CharField(db_index=True, max_length=128, verbose_name='raw_string')),
                ('convert_string', models.CharField(db_index=True, max_length=128, verbose_name='convert_string')),
            ],
            options={
                'verbose_name': 'строка',
                'verbose_name_plural': 'строки',
                'ordering': ('-raw_string',),
            },
        ),
    ]
