# Generated by Django 4.0.4 on 2022-05-19 15:26

from django.db import migrations, models
import django.db.models.deletion
import utils.mixins
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='название')),
                ('desc', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BinaryField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('-name',),
            },
            bases=(utils.mixins.IsActiveFalseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, verbose_name='заголовок')),
                ('image', models.ImageField(blank=True, upload_to=utils.utils.article_image_directory_path, verbose_name='изображение')),
                ('body', models.TextField(verbose_name='текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='отредактирована')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articlesapp.topic')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('-topic',),
            },
            bases=(utils.mixins.IsActiveFalseMixin, models.Model),
        ),
    ]
