# Generated by Django 4.0.4 on 2022-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
