# Generated by Django 4.0.4 on 2022-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='broker_exchange_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.06, max_digits=3, verbose_name='Комиссия брокера и биржи процент'),
        ),
    ]
