# Generated by Django 4.0.4 on 2022-05-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_broker_exchange_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='broker_exchange_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.06, max_digits=3, verbose_name='Комиссия брокера и биржи %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена продажи в рублях за 1 ед.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax',
            field=models.PositiveSmallIntegerField(default=13, verbose_name='% налог на прибыль'),
        ),
    ]
