# Generated by Django 4.0.4 on 2022-05-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_broker_exchange_commission_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_active',
        ),
    ]
